//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtuHotelRebuilt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guest
    {
        public int id { get; set; }
        public int ReservationID { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public System.DateTime birthdate { get; set; }
        public string phone { get; set; }
        public bool gender { get; set; }
    
        public virtual Reservation Reservation { get; set; }
    }
}
