//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtuHotelRebuilt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Staff()
        {
            this.User = new HashSet<User>();
        }
    
        public string fname { get; set; }
        public string lname { get; set; }
        public System.DateTime birthdate { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public int DepartmentID { get; set; }
        public string dayoff { get; set; }
        public string tcNumber { get; set; }
        public string email { get; set; }
        public bool gender { get; set; }
    
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> User { get; set; }
    }
}
